### ISSUE TITLE
this.context is null

### ISSUE THREAD

**Issue by jamesj2** [php-flasher/flasher-pnotify-js#3]
I can't use a CDN in my environment so I'm trying to use the NPM packages.   If I use the CDN scripts it works fine.  Without the CDN scripts I'm get the following error when I try to display a message.

> Uncaught TypeError: this.context is null
>     value http://127.0.0.1:8000/js/app.js:70
>     update http://127.0.0.1:8000/js/app.js:70
>     s http://127.0.0.1:8000/js/app.js:70
>     s http://127.0.0.1:8000/js/app.js:70
>     f http://127.0.0.1:8000/js/app.js:70
>     gt http://127.0.0.1:8000/js/app.js:70
>     node_modules flasher/flasher-pnotify/dist/flasher-pnotify.js/</PNotify</</t.success@http://127.0.0.1:8000/js/app.js:70
>     node_modules flasher/flasher-pnotify/dist/flasher-pnotify.js/</PnotifyFactory</PnotifyFactory.prototype.render@http://127.0.0.1:8000/js/app.js:89
>     node_modules flasher/flasher/dist/flasher.js/</Flasher</Flasher.prototype.renderEnvelopes/<@http://127.0.0.1:8000/js/app.js:210
>     node_modules flasher/flasher/dist/flasher.js/</Flasher</Flasher.prototype.renderEnvelopes@http://127.0.0.1:8000/js/app.js:207
>     node_modules flasher/flasher/dist/flasher.js/</Flasher</Flasher.prototype.render/</<@http://127.0.0.1:8000/js/app.js:154
>     node_modules flasher/flasher/dist/flasher.js/</Flasher</Flasher.prototype.addScripts@http://127.0.0.1:8000/js/app.js:181
>     node_modules flasher/flasher/dist/flasher.js/</Flasher</Flasher.prototype.render/<@http://127.0.0.1:8000/js/app.js:152
>     node_modules flasher/flasher/dist/flasher.js/</Flasher</Flasher.prototype.addStyles@http://127.0.0.1:8000/js/app.js:162
>     node_modules flasher/flasher/dist/flasher.js/</Flasher</Flasher.prototype.render@http://127.0.0.1:8000/js/app.js:151
>     <anonymous> http://127.0.0.1:8000/:124
> app.js:70:16358

I created a [repo](https://github.com/jamesj2/laravel-flasher-pnotify-js-issue) to demonstrate the issue.  

Summary of steps I did...
* Create a laravel  project then
```
composer require php-flasher/flasher-pnotify-laravel
php artisan vendor:publish --tag='flasher-config'
npm i @flasher/flasher @flasher/flasher-pnotify -S
```
* from there I added the following to app.js
```
import { default as Flasher } from '@flasher/flasher';
import '@flasher/flasher-pnotify';
window['Flasher'] = Flasher;
```
* Then modified the configs to remove the 'root_scripts' and 'scripts' defaults, changed home route to add a message, and added @flasher_render to blade template.

**Comment by yoeunes** [comment]
Hello @jamesj2 you did a great job because I didn't have time to document the js part of the library, I was able to fix the problem just by ordering the javascript tags, here is a PR for what I did: https://github.com/jamesj2/laravel-flasher-pnotify-js-issue/pull/1
Can you please confirm if this is working for you or not?

**Comment by jamesj2** [comment]
I can confirm the fix works.  Since it's a timing issue I tried wrapping the render instance with a DOMContentLoaded event in the HTML presenter it works without having to reorder the scripts.  Thanks!

```
        return <<<CODE_SAMPLE
{$scripts}
<script type="text/javascript">
window.addEventListener('DOMContentLoaded', () => {
    Flasher.getInstance().render({$options});
});
</script>
CODE_SAMPLE;
```
