### ISSUE TITLE
how to access the PNotify instance

### ISSUE THREAD

**Issue by jamesj2** [php-flasher/flasher-pnotify-js#4]
How does one access the PNotify instance?  I'd like to use some defaults like below.  And I'd like to use PNotify directly in my JS without having to instantiate twice.  Thanks!

```
import '@flasher/flasher-notyf';
import * as PNotify from '@pnotify/core/dist/PNotify.js';
import * as PNotifyBootstrap4 from '@pnotify/bootstrap4';
import * as PNotifyMobile from '@pnotify/mobile';
import * as PNotifyAnimate from '@pnotify/animate';
import '@pnotify/core/dist/BrightTheme.css';
import '@pnotify/bootstrap4/dist/PNotifyBootstrap4.css';

defaultModules.set(PNotifyBootstrap4, {});
defaultModules.set(PNotifyMobile, {});
defaultModules.set(PNotifyAnimate, {});

PNotify.defaultStack.close(true);
PNotify.defaultStack.maxOpen = Infinity;
PNotify.defaultStack.modal = false;
```

**Comment by yoeunes** [comment]
Hello @jamesj2, I had a hard time integrating the "**Pnotify**" library into PHP Flasher, I know the code in this repo "**flasher-pnotify-js**" is not perfect.

Maybe if you find a better approach, you could create a PR, to simply this integration.

**Comment by jamesj2** [comment]
Thanks for the fast reply.  I'd like to work on it but I don't have time right now.  I'm thinking the best approach might be to use a previous instance if it already exists.  If PNotify exists then use that instance, if not then start an instance.  This would allow advanced and basic usage.

**Comment by yoeunes-spin** [comment]
i'll what i can do when i will have time, maybe for a v2
